#!/bin/bash

echo "starting gather"

docker run --rm -d --name dispatch -p 8081:8081 \
      -e CONSUMER_KEY=... \
      -e CONSUMER_SECRET=... \
      -e ACCESS_TOKEN=... \
      -e ACCESS_TOKEN_SECRET=... spmasterman/tweet-gathering:latest



