
server:
  port: 9099

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

queue:
  twitter: twitter-stream
exchange:
  twitter: twitter-exchange

info:
  project: "tweet-dispatcher"
  kotlin: @kotlin.version@

management:
  endpoints:
    web:
      expose: "*"

---

spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq