
server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  redis:
    host: localhost
    port: 6379

queue:
  twitter: twitter-track-hashtag
exchange:
  twitter: twitter-track-exchange
routing_key:
  track: track.*

---

spring:
  profiles: docker
  redis:
    host: redis
  rabbitmq:
    host: rabbitmq